language: node_js
node_js:
- 10.16.0

os: linux
dist: trusty

cache:
  npm: false

before_install:
- npm i -g npm@6.9.0

stages:
- api

script:
- npm test || if [$? != 0]; then exit 0; fi

jobs:
  include:
  - stage: api

addons:
  artifacts:
    paths:
    - ./allure-results
    target_paths: $TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER/results